export const qaThreadActionType = {
  CLEAR_DATA: 'CLEAR_DATA',
  CREATE_THREAD_START: 'CREATE_THREAD_START',
  CREATE_THREAD_SUCCESS: 'CREATE_THREAD_SUCCESS',
  CREATE_THREAD_ERROR: 'CREATE_THREAD_ERROR',
  CLEAR_THREAD_ERROR: 'CLEAR_THREAD_ERROR',
  CLEAR_CREATE_SUCCESS: 'CLEAR_CREATE_SUCCESS',
  SEARCH_THREAD: 'SEARCH_THREAD',
  READ_MY_THREADS: 'READ_MY_THREADS',
  READ_THREADS_BY_MODULE: 'READ_THREADS_BY_MODULE',
  LISTEN_MY_THREAD: 'LISTEN_MY_THREAD',
  UPDATE_THREAD_REDUCER: 'UPDATE_THREAD_REDUCER',
};
